### ISSUE TITLE
Test model on Google Colab

### ISSUE THREAD

**Issue by givkashi** [siyuanliii/masa#22]
Hi, Thanks for your amazing work. 
I wanted to test the model on Colab but I got the following error. 
Please let me know how I can fix it. 
You can find notebook [here](https://colab.research.google.com/drive/1xyYRhtNDWdU72XKM6nDBikdX8Ylv2ShA?usp=sharing)

]
8s
!python demo/video_demo_with_text.py demo/minions_rush_out.mp4 --out demo_outputs/minions_rush_out_outputs.mp4 --masa_config configs/masa-gdino/masa_gdino_swinb_inference.py --masa_checkpoint saved_models/masa_models/gdino_masa.pth --texts "yellow_minions" --score-thr 0.2 --unified --show_fps
Traceback (most recent call last):
  File "/content/masa/demo/video_demo_with_text.py", line 19, in <module>
    from mmdet.apis import init_detector
  File "/usr/local/lib/python3.10/dist-packages/mmdet/apis/__init__.py", line 2, in <module>
    from .det_inferencer import DetInferencer
  File "/usr/local/lib/python3.10/dist-packages/mmdet/apis/det_inferencer.py", line 22, in <module>
    from mmdet.evaluation import INSTANCE_OFFSET
  File "/usr/local/lib/python3.10/dist-packages/mmdet/evaluation/__init__.py", line 4, in <module>
    from .metrics import *  # noqa: F401,F403
  File "/usr/local/lib/python3.10/dist-packages/mmdet/evaluation/metrics/__init__.py", line 5, in <module>
    from .coco_metric import CocoMetric
  File "/usr/local/lib/python3.10/dist-packages/mmdet/evaluation/metrics/coco_metric.py", line 16, in <module>
    from mmdet.datasets.api_wrappers import COCO, COCOeval, COCOevalMP
  File "/usr/local/lib/python3.10/dist-packages/mmdet/datasets/__init__.py", line 31, in <module>
    from .utils import get_loading_pipeline
  File "/usr/local/lib/python3.10/dist-packages/mmdet/datasets/utils.py", line 5, in <module>
    from mmdet.datasets.transforms import LoadAnnotations, LoadPanopticAnnotations
  File "/usr/local/lib/python3.10/dist-packages/mmdet/datasets/transforms/__init__.py", line 6, in <module>
    from .formatting import (ImageToTensor, PackDetInputs, PackReIDInputs,
  File "/usr/local/lib/python3.10/dist-packages/mmdet/datasets/transforms/formatting.py", line 11, in <module>
    from mmdet.structures.bbox import BaseBoxes
  File "/usr/local/lib/python3.10/dist-packages/mmdet/structures/bbox/__init__.py", line 2, in <module>
    from .base_boxes import BaseBoxes
  File "/usr/local/lib/python3.10/dist-packages/mmdet/structures/bbox/base_boxes.py", line 9, in <module>
    from mmdet.structures.mask.structures import BitmapMasks, PolygonMasks
  File "/usr/local/lib/python3.10/dist-packages/mmdet/structures/mask/__init__.py", line 3, in <module>
    from .structures import (BaseInstanceMasks, BitmapMasks, PolygonMasks,
  File "/usr/local/lib/python3.10/dist-packages/mmdet/structures/mask/structures.py", line 12, in <module>
    from mmcv.ops.roi_align import roi_align
  File "/usr/local/lib/python3.10/dist-packages/mmcv/ops/__init__.py", line 3, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/usr/local/lib/python3.10/dist-packages/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "/usr/local/lib/python3.10/dist-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

**Comment by rolson24** [comment]
You need to downgrade the CUDA version to 11.8:
```
!wget https://developer.download.nvidia.com/compute/cuda/11.8.0/local_installers/cuda-repo-ubuntu2204-11-8-local_11.8.0-520.61.05-1_amd64.deb
!sudo dpkg -i cuda-repo-ubuntu2204-11-8-local_11.8.0-520.61.05-1_amd64.deb
!sudo cp /var/cuda-repo-ubuntu2204-11-8-local/cuda-*-keyring.gpg /usr/share/keyrings/
!sudo apt-get update
!sudo apt-get -y install cuda-11-8
!export CUDA_PATH=/usr/local/cuda-11.8/
```

**Comment by rolson24** [comment]
Actually don't need to do that. Try this [notebook](https://colab.research.google.com/drive/1HpNu9jeIuZcBpzcN2ZijSv2cKkwZgVd6?usp=sharing)

**Comment by siyuanliii** [comment]
@rolson24 Thanks for creating the Colab! It looks great!

**Comment by givkashi** [comment]
> Actually don't need to do that. Try this [notebook](https://colab.research.google.com/drive/1HpNu9jeIuZcBpzcN2ZijSv2cKkwZgVd6?usp=sharing)

Thanks

**Comment by MattLiutt** [comment]
@rolson24 Thanks for the notebook! However, I found the notebook will stuck in building mmcv, like loading the following forever: 
`Building wheels for collected packages: mmcv`. Do you have any clue on this?

**Comment by AshishreddyM26** [comment]
Hey, @MattLiutt 

Have you figured out the issue? Were you able to run MASA without any issues, please reach out, I am facing similar issues.

Thanks
Ashish

**Comment by MattLiutt** [comment]
> Hey, [@MattLiutt](https://github.com/MattLiutt)
> 
> Have you figured out the issue? Were you able to run MASA without any issues, please reach out, I am facing similar issues.
> 
> Thanks Ashish

not yet, in the end I gave up.

**Comment by AshishreddyM26** [comment]
Oh no, after all, I figured it out.

**Comment by MattLiutt** [comment]
How do you solve it? Thanks!

**Comment by AshishreddyM26** [comment]
I also faced similar issues in google collab, as it comes with pre-built packages. So I did that locally by manually installing the mmdet and mmcv packages as described in https://github.com/siyuanliii/masa/blob/main/docs/install.md 
Do option 2 (manual installation)
