### ISSUE TITLE
About MasaTransformBroadcaster

### ISSUE THREAD

**Issue by locokun** [siyuanliii/masa#44]
Thanks a lot for your great job and patient answers. I followed your work using my new domain dataset to train MASA-SAM, but I faced a problem with MasaTransformBroadcaster. I first thougt it might because my dataset is gray tif file, so I turned it into RGB tif file before feeding them into the model. But the error still remains. I tried a few days trying to figure out where the problem is, but have no idea. I wonder if you could tell me where the problem might be from the following error info:

Error occurred while running pipeline MasaTransformBroadcaster(transforms = Compose(
    SeqRandomAffine(max_rotate_degree=10.0, max_translate_ratio=0.1, scaling_ratio_range=(0.5, 1.5), max_shear_degree=2.0, border=(0, 0), border_val=(114, 114, 114), bbox_clip_border=True)
    SeqMixUp(dynamic_scale=(704, 520), ratio_range=(0.8, 1.6), flip_ratio=0.5, pad_val=114.0, max_iters=15, bbox_clip_border=False)
    YOLOXHSVRandomAug(hue_delta=5, saturation_delta=30, value_delta=30)
    RandomResize(scale=(704, 520), ratio_range=(0.1, 2.0), resize_cfg={'type': 'Resize', 'keep_ratio': True, 'clip_object_border': False})
    RandomCrop(crop_size=(704, 520), crop_type=absolute, allow_negative_crop=False, recompute_bbox=False, bbox_clip_border=False)
    RandomFlip(prob=0.5, direction=horizontal)
    Pad(size=(704, 520), size_divisor=None, pad_to_square=False, pad_val={'img': 114, 'seg': 255}), padding_mode=constant)
    FilterMatchAnnotations(min_gt_bbox_wh=(1, 1), keep_empty=False)
), mapping = None, remapping = None, auto_remap = True, allow_nonexist_keys = False, share_random_params = False) with error: Transforms wrapped by MasaTransformBroadcaster should not return None.

Original Traceback (most recent call last):
  File "/home/user9/anaconda3/envs/masaenv/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/user9/anaconda3/envs/masaenv/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user9/anaconda3/envs/masaenv/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/home/user9/YAQ/cell/masa/masa/datasets/dataset_wrappers.py", line 254, in __getitem__
    raise RuntimeError(
RuntimeError: The training pipeline of the dataset wrapper always return None.Please check the correctness of the dataset and its pipeline.

**Comment by locokun** [comment]
I printed out the "results" to put into transform function, and it is:
results:  {'img_path': 'data/livecell/images/livecell_train_val_images/SkBr3_Phase_E3_2_03d12h00m_4.tif', 'img_id': 1167290, 'seg_map_path': None, 'height': 520, 'width': 704, 'instances': [], 'sample_idx': 2384, 'img': array([[[107, 107, 107],
        [122, 122, 122],
        [123, 123, 123],
        ...,
        [135, 135, 135],
        [132, 132, 132],
        [136, 136, 136]]], dtype=uint8), 'img_shape': (520, 704), 'ori_shape': (520, 704), 'gt_bboxes': HorizontalBoxes(
tensor([], size=(0, 4))), 'gt_ignore_flags': array([], dtype=bool), 'gt_bboxes_labels': array([], dtype=int64), 'gt_instances_ids': array([], dtype=int32)}

I wonder if it's because the values related to gt_bboxes are empty. Are they need to be nonempty tensors? Perhaps you could tell me why these gt_bboxes are none and whether they matter.

**Comment by locokun** [comment]
Thank you for your answer! I solved this problem thanks to your help~
